//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data.Resources.Navigation {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Navigation_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Navigation_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Data.Resources.Navigation.Navigation_ru", typeof(Navigation_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Navigation_Product_Text {
            get {
                return ResourceManager.GetString("Navigation_Product_Text", resourceCulture);
            }
        }
        
        internal static string Navigation_Order_Text {
            get {
                return ResourceManager.GetString("Navigation_Order_Text", resourceCulture);
            }
        }
        
        internal static string Navigation_Home_Text {
            get {
                return ResourceManager.GetString("Navigation_Home_Text", resourceCulture);
            }
        }
        
        internal static string Navigation_Dashboard_Text {
            get {
                return ResourceManager.GetString("Navigation_Dashboard_Text", resourceCulture);
            }
        }
        
        internal static string Navigation_Category_Headphones_Text {
            get {
                return ResourceManager.GetString("Navigation_Category_Headphones_Text", resourceCulture);
            }
        }
        
        internal static string Navigation_Category_Keyboard_Text {
            get {
                return ResourceManager.GetString("Navigation_Category_Keyboard_Text", resourceCulture);
            }
        }
        
        internal static string Navigation_Category_Laptop_Text {
            get {
                return ResourceManager.GetString("Navigation_Category_Laptop_Text", resourceCulture);
            }
        }
        
        internal static string Navigation_Category_Monitor_Text {
            get {
                return ResourceManager.GetString("Navigation_Category_Monitor_Text", resourceCulture);
            }
        }
        
        internal static string Navigation_Category_Mouse_Text {
            get {
                return ResourceManager.GetString("Navigation_Category_Mouse_Text", resourceCulture);
            }
        }
        
        internal static string Navigation_About_Us_Text {
            get {
                return ResourceManager.GetString("Navigation_About_Us_Text", resourceCulture);
            }
        }
        
        internal static string Navigation_Contact_Text {
            get {
                return ResourceManager.GetString("Navigation_Contact_Text", resourceCulture);
            }
        }
        
        internal static string Navigation_Register_Text {
            get {
                return ResourceManager.GetString("Navigation_Register_Text", resourceCulture);
            }
        }
        
        internal static string Navigation_Logout_Text {
            get {
                return ResourceManager.GetString("Navigation_Logout_Text", resourceCulture);
            }
        }
        
        internal static string Navigation_Login_Text {
            get {
                return ResourceManager.GetString("Navigation_Login_Text", resourceCulture);
            }
        }
    }
}
