//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Views.Reviewer.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Reviewer {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reviewer() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WebApp.Views.Reviewer.Resources.Reviewer", typeof(Reviewer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Reviewer_Column_Language {
            get {
                return ResourceManager.GetString("Reviewer_Column_Language", resourceCulture);
            }
        }
        
        public static string Reviewer_Column_Key {
            get {
                return ResourceManager.GetString("Reviewer_Column_Key", resourceCulture);
            }
        }
        
        public static string Reviewer_Column_Content {
            get {
                return ResourceManager.GetString("Reviewer_Column_Content", resourceCulture);
            }
        }
        
        public static string Reviewer_Column_Version {
            get {
                return ResourceManager.GetString("Reviewer_Column_Version", resourceCulture);
            }
        }
        
        public static string Reviewer_Column_Action {
            get {
                return ResourceManager.GetString("Reviewer_Column_Action", resourceCulture);
            }
        }
        
        public static string Reviewer_Heading_Review {
            get {
                return ResourceManager.GetString("Reviewer_Heading_Review", resourceCulture);
            }
        }
        
        public static string Reviewer_Button_Approve {
            get {
                return ResourceManager.GetString("Reviewer_Button_Approve", resourceCulture);
            }
        }
        
        public static string Reviewer_Button_Reject {
            get {
                return ResourceManager.GetString("Reviewer_Button_Reject", resourceCulture);
            }
        }
    }
}
