//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Data.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Heading_Shop {
            get {
                return ResourceManager.GetString("Heading_Shop", resourceCulture);
            }
        }
        
        public static string Shared_Navigation_Language_Selection {
            get {
                return ResourceManager.GetString("Shared_Navigation_Language_Selection", resourceCulture);
            }
        }
        
        public static string Shared_Navigation_Category_Headphones {
            get {
                return ResourceManager.GetString("Shared_Navigation_Category_Headphones", resourceCulture);
            }
        }
        
        public static string Shared_Navigation_Category_Keyboard {
            get {
                return ResourceManager.GetString("Shared_Navigation_Category_Keyboard", resourceCulture);
            }
        }
        
        public static string Shared_Navigation_Category_Laptop {
            get {
                return ResourceManager.GetString("Shared_Navigation_Category_Laptop", resourceCulture);
            }
        }
        
        public static string Shared_Navigation_Category_Monitor {
            get {
                return ResourceManager.GetString("Shared_Navigation_Category_Monitor", resourceCulture);
            }
        }
        
        public static string Shared_Navigation_Category_Mouse {
            get {
                return ResourceManager.GetString("Shared_Navigation_Category_Mouse", resourceCulture);
            }
        }
        
        public static string Shared_Navigation_Products {
            get {
                return ResourceManager.GetString("Shared_Navigation_Products", resourceCulture);
            }
        }
        
        public static string Shared_Navigation_Orders {
            get {
                return ResourceManager.GetString("Shared_Navigation_Orders", resourceCulture);
            }
        }
        
        public static string Shared_Navigation_Dashboard {
            get {
                return ResourceManager.GetString("Shared_Navigation_Dashboard", resourceCulture);
            }
        }
        
        public static string Shared_Navigation_Home {
            get {
                return ResourceManager.GetString("Shared_Navigation_Home", resourceCulture);
            }
        }
    }
}
