//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Data.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Navigation_Home {
            get {
                return ResourceManager.GetString("Navigation_Home", resourceCulture);
            }
        }
        
        internal static string Navigation_Dashboard {
            get {
                return ResourceManager.GetString("Navigation_Dashboard", resourceCulture);
            }
        }
        
        internal static string Navigation_Order {
            get {
                return ResourceManager.GetString("Navigation_Order", resourceCulture);
            }
        }
        
        internal static string Navigation_Product {
            get {
                return ResourceManager.GetString("Navigation_Product", resourceCulture);
            }
        }
        
        internal static string Navigation_Category_Monitor {
            get {
                return ResourceManager.GetString("Navigation_Category_Monitor", resourceCulture);
            }
        }
        
        internal static string Navigation_Category_Laptop {
            get {
                return ResourceManager.GetString("Navigation_Category_Laptop", resourceCulture);
            }
        }
        
        internal static string Navigation_Category_Keyboard {
            get {
                return ResourceManager.GetString("Navigation_Category_Keyboard", resourceCulture);
            }
        }
        
        internal static string Navigation_Category_Mouse {
            get {
                return ResourceManager.GetString("Navigation_Category_Mouse", resourceCulture);
            }
        }
        
        internal static string Navigation_Category_Headphones {
            get {
                return ResourceManager.GetString("Navigation_Category_Headphones", resourceCulture);
            }
        }
        
        internal static string Navigation_About_Us {
            get {
                return ResourceManager.GetString("Navigation_About_Us", resourceCulture);
            }
        }
        
        internal static string Navigation_Contact {
            get {
                return ResourceManager.GetString("Navigation_Contact", resourceCulture);
            }
        }
        
        internal static string Navigation_Register {
            get {
                return ResourceManager.GetString("Navigation_Register", resourceCulture);
            }
        }
        
        internal static string Navigation_Login {
            get {
                return ResourceManager.GetString("Navigation_Login", resourceCulture);
            }
        }
        
        internal static string Navigation_Logout {
            get {
                return ResourceManager.GetString("Navigation_Logout", resourceCulture);
            }
        }
        
        internal static string Heading_Categories {
            get {
                return ResourceManager.GetString("Heading_Categories", resourceCulture);
            }
        }
        
        internal static string Heading_Products {
            get {
                return ResourceManager.GetString("Heading_Products", resourceCulture);
            }
        }
        
        internal static string Heading_Shop {
            get {
                return ResourceManager.GetString("Heading_Shop", resourceCulture);
            }
        }
        
        internal static string Button_Product_Add_To_Cart {
            get {
                return ResourceManager.GetString("Button_Product_Add_To_Cart", resourceCulture);
            }
        }
        
        internal static string Button_Product_Details {
            get {
                return ResourceManager.GetString("Button_Product_Details", resourceCulture);
            }
        }
    }
}
